name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, zip, pcntl, bcmath, gd
          coverage: none

      - name: Configure composer
        run: php scripts/configure-composer.php

      - name: Install composer on the host
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      - name: Install dependencies
        run: composer install

      - name: Build binaries
        run: composer build
        env:
          VERSION: ${{ github.ref_name }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: builds/pfy_*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
